// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0FoPq8aWQP_aUiDs9bEO2qnrx9itwcS8',
    appId: '1:1048907156078:web:94d54ce321097bc369347f',
    messagingSenderId: '1048907156078',
    projectId: 'flutterauthentication-cb063',
    authDomain: 'flutterauthentication-cb063.firebaseapp.com',
    storageBucket: 'flutterauthentication-cb063.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCounErkDbtyVy4nczmFqwEvJHDqOjxmns',
    appId: '1:1048907156078:android:d67c6b56b9e9467d69347f',
    messagingSenderId: '1048907156078',
    projectId: 'flutterauthentication-cb063',
    storageBucket: 'flutterauthentication-cb063.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNkvxd9gsSo7Nvgdm3O9vMK-TqK9QvijQ',
    appId: '1:1048907156078:ios:5e0945f738113bef69347f',
    messagingSenderId: '1048907156078',
    projectId: 'flutterauthentication-cb063',
    storageBucket: 'flutterauthentication-cb063.appspot.com',
    iosBundleId: 'com.example.onboadingScreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNkvxd9gsSo7Nvgdm3O9vMK-TqK9QvijQ',
    appId: '1:1048907156078:ios:696c17c06fc0795369347f',
    messagingSenderId: '1048907156078',
    projectId: 'flutterauthentication-cb063',
    storageBucket: 'flutterauthentication-cb063.appspot.com',
    iosBundleId: 'com.example.onboadingScreen.RunnerTests',
  );
}
